name: watertap-ui-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - nodejs=17.9.0
  - pip:
    - -r backend/requirements.txt
    - git+https://github.com/watertap-org/watertap@09fb69c9ff2aaa8273c9d71b8d44b9cecf4917af
