name: App testing CI

on:
  push:
    branches: [ "UI-testing" ]
  pull_request:
    branches: [ "UI-testing" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [12.x, 14.x, 16.x]
        python-version: ['3.x', 'pypy3.7', 'pypy3.8' ]

    steps:
      # - uses: actions/checkout@v3
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: 'npm'
      #     cache-dependency-path: './electron/ui/package-lock.json'

      # # install electron
      # - name: install electron
      #   working-directory: ./electron
      #   run: npm ci

      # # install frontend and test
      # - name: npm install & test
      #   working-directory: ./electron/ui
      #   run: |
      #     npm ci
      #     npm test

      # install backend
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'
          cache-dependency-path: './backend/requirements.txt'  

      # this Action should follow steps to set up Python build environment
      # - name: Install Python dependencies
      #   uses: py-actions/py-dependency-install@v3
      #   with:
      #     path: "backend/requirements.txt"

      - name: install backend
        working-directory: backend
        run: pip install -r requirements.txt
