name: App testing CI

on:
  push:
    branches: [ "UI-testing" ]
  pull_request:
    branches: [ "UI-testing" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./electron/ui/
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: ls -a
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './electron/ui/package-lock.json'
    - run: npm ci
    # - run: npm run build --if-present
    - run: npm test
